### ISSUE TITLE
Can you add an requirements file?

### ISSUE THREAD

**Issue by JackTesla** [Zhendong-Wang/Diffusion-GAN#17]
First of all , It's an outstanding work! Good Job!
Can you add an requirements file?
Thank you!

**Comment by Zhendong-Wang** [comment]
Thanks for your interest! We have the environment requirements listed here https://github.com/Zhendong-Wang/Diffusion-GAN#requirements, which is the same as the StyleGAN2. Usually different machines have different situations when installing Pytorch, so we don't give a requirement file here.
