### ISSUE TITLE
Conditioning signal in Diffusion ProjectedGAN

### ISSUE THREAD

**Issue by yahshibu** [Zhendong-Wang/Diffusion-GAN#18]
Great work! Thank you for sharing your code.

I have a question about Diffusion ProjectedGAN.

In Diffusion StyleGAN2 and Diffusion InsGAN, time-step information $t$ is provided to discriminators.

https://github.com/Zhendong-Wang/Diffusion-GAN/blob/05c6b0f07b855266563dc40ee97e9eaffe379932/diffusion-stylegan2/training/networks.py#L729-L732

https://github.com/Zhendong-Wang/Diffusion-GAN/blob/05c6b0f07b855266563dc40ee97e9eaffe379932/diffusion-insgen/training/networks.py#L732-L735

On the other hand, $t$ is not given to a discriminator in Diffusion ProjectedGAN, as the paper mentions in Appendix. $t$ is just used in a feature network where feature vectors are diffused. 

https://github.com/Zhendong-Wang/Diffusion-GAN/blob/05c6b0f07b855266563dc40ee97e9eaffe379932/diffusion-projected-gan/pg_modules/discriminator.py#L184

I'm wondering why a discriminator in Diffusion ProjectedGAN works well without time-step information $t$. I'd appreciated it if you would give some insights.

Best regards.

**Comment by Zhendong-Wang** [comment]
Hi there, thanks for your interest and sorry for the late reply. Empirically we found the discriminator in ProjectedGAN doesn't need the $t$ as the condition. The discriminator in ProjectedGAN is different from StyleGAN2, which is light-weighed. Injection of $t$ will support our Theorem 2 but sometimes without $t$ condition, the algorithm still works.

**Comment by yahshibu** [comment]
Thank you for your reply!

> Injection of $t$ will support our Theorem 2 but sometimes without condition
Yes, this is surprising to me. Now, I understand that you empirically found the algorithm works even without $t$.
