### ISSUE TITLE
Generation includes reverse process of Diffusion?

### ISSUE THREAD

**Issue by justin4ai** [Zhendong-Wang/Diffusion-GAN#39]
Hello, thanks for providing your amazing work.

I wonder if there is a reverse process in generate.py to generate images just like other diffusion models.
Seemingly you only use GAN models for generation, so I just want to make whether my understand is proper clear!

Thanks!

**Comment by Zhendong-Wang** [comment]
Hi Justin,

Diffusion-GAN is motivated by using diffusion technologies to improve the
training of GAN. It trains a one-step GAN generator.

Best,

Zhendong

**Comment by justin4ai** [comment]
Dear Zhendong,

Thanks for making it clear! Then generation will be done via GAN, not via reverse process of diffusion model.

**Comment by justin4ai** [comment]
I close this issue
