### ISSUE TITLE
Download link for pretrained model.

### ISSUE THREAD

**Issue by KyeonghaRho** [Zhendong-Wang/Diffusion-GAN#7]
Hi, I think you did a great research and I want to test with your model.

But when I tried to download the pretrained Diffusion-StyleGAN2 weights trained on CelebA 64x64 dataset,
I got an error that "requests.exceptions.HTTPError: 409 Client Error: Public access is not permitted on this storage account. for url: https://tsciencescu.blob.core.windows.net/projectshzheng/DiffusionGAN/diffusion-stylegan2-celeba64.pkl"

Would you please check this?

**Comment by Zhendong-Wang** [comment]
Hi there,

Thanks for your interest. The accessibility of the shared folder was changed for some company reason. Will update the link as soon as possible.

**Comment by Zhendong-Wang** [comment]
Hi there, the pretrained checkpoints now are moved to Hugging Face for public downloadings. You could download from Hugging Face or our updated quick access links.
